-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES)as TOTAL_SALES
FROM BOOK a JOIN BOOK_SALES b on a.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-01"
group by CATEGORY
order by CATEGORY asc;
